### ISSUE TITLE
连续对话可以支持吗

### ISSUE THREAD

**Issue by Creazygao** [poorjobless/wechatbot#3]
非常感谢大大，由于不动go语言所以不知道怎么让他支持连续对话，能否有空更新此功能

**Comment by elllusion** [comment]
连续对话可以参考官方ChatGPT的做法，把新提问和旧提问（或及其回答（可选这不附加））一起作为新提问发给模型处理。 但这样如果不限制聊天占用的内存大小那会随着聊天次数的增加会使得内存占用过大和其他一些问题。

想要实现连续对话那就得要把未接收到结束话题空间的词汇（比如：谢谢你， 很不错。。。之类的也就是用户对回答的结果很满意或很肯定方面的词汇）前的对话视为一个话题空间， 把这个空间的对话内容进行保持，如下所说的那样。

这个网站 https://lwebapp.com/zh/post/chatgpt-api 有具体实现， 以下是部分摘抄自该网站：
```
为什么要提供一个对话列表呢？因为 API 调用都是单次的接口请求，不会自动记录之前的聊天信息，没有上下文，要让 ChatGPT 在单次的请求中了解你的上下文，就需要提供这样一个完整的对话列表，比如这样一个对话

import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
每条对话消息都需要提供角色和内容，角色分三种：系统system、用户user 或者 助手assistant。

system：系统消息相当于一个管理员，可以设置助手的行为和特征。在上面的例子中，助手被指示你是一个有用的助手。
user：用户消息就是我们自己，可以由用户发出提问，或者直接让开发者提前内置一些 Prompts 指令。一些可以参考的 [ChatGPT Prompts](https://chatopenai.pro/chatgpt-prompts/)
assistant：助手消息就是 ChatGPT API 在之前提供的回复，在这里存储起来。这个回复也可以自己修改或者自己编一段对话出来，来让整个对话更通顺。
如果不需要对话的话，只需要提供单个的user消息即可，就像刚刚 Python 代码里演示的。
```

上面这个做法可以实现类似人类的短期记忆的对话， 如果想要实现长期记忆的对话那就把对话内容按话题空间开始和结束的时间保存到数据库。至于咋设计长期记忆的记忆索引那是研发者要解决的问题。

**Comment by elllusion** [comment]
大型语言模型实现连续对话的基本思路是通过将上下文信息输入到模型中，让模型根据历史对话内容生成回复。一般情况下，这种方法需要使用特殊的算法来管理对话状态和上下文。

具体来说，实现连续对话的方法包括：

上下文感知：在生成回复时，除了考虑当前输入的语句外，还需要将之前的对话历史作为上下文输入到模型中，以便更好地理解对话背景和用户意图。

对话状态管理：为了实现连续对话，需要跟踪对话状态并在每轮对话中更新它。例如，记录用户提出的问题、系统的回答、目前所处的对话阶段等信息。

语义解析：大型语言模型可以自动识别和理解用户的自然语言输入，并从中提取有用的信息。在连续对话中，模型需要及时解析用户的意图，并能够在后续的对话中针对同一主题提供相关信息。

回复生成：模型根据上下文信息和用户意图生成回复，同时，需要保证回复的连贯性和适当性，避免产生无意义甚至冒犯用户的回复。

以上是实现连续对话的基本方法，具体的实现方式会因应用场景和技术方案而异。
