### ISSUE TITLE
这个错误是什么原因

### ISSUE THREAD

**Issue by bxs17** [poorjobless/wechatbot#5]
2023/03/04 04:30:08 Received User ～大兵 Text Msg : 你的名字是？出生日期是？
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x55c0a9]

goroutine 34 [running]:
github.com/poorjobless/wechatbot/chatgpt.Completions({0xc0000bdcb0, 0x24})
        F:/wechatbot-main/chatgpt/chatgpt.go:22 +0x149
github.com/poorjobless/wechatbot/handlers.(*UserMessageHandler).ReplyText(0x3a?, 0xc0002c0500)
        F:/wechatbot-main/handlers/user_msg_handler.go:39 +0xf1
github.com/poorjobless/wechatbot/handlers.(*UserMessageHandler).handle(0x58cb20?, 0xc00008ad80?)
        F:/wechatbot-main/handlers/user_msg_handler.go:20 +0x2a
github.com/poorjobless/wechatbot/handlers.Handler(0xc0002c0500)
        F:/wechatbot-main/handlers/handler.go:53 +0x21a
github.com/eatmoreapple/openwechat.(*Bot).syncCheck(0xc000112000)
        C:/Users/llelle/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.3.0/bot.go:291 +0x1d8
github.com/eatmoreapple/openwechat.(*Bot).WebInit.func1()
        C:/Users/llelle/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.3.0/bot.go:243 +0x7d
sync.(*Once).doSlow(0x0?, 0x0?)
        C:/Program Files/Go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(0x0?, 0x0?)
        C:/Program Files/Go/src/sync/once.go:65 +0x1f
created by github.com/eatmoreapple/openwechat.(*Bot).WebInit
        C:/Users/llelle/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.3.0/bot.go:238 +0x1cd
exit status 2

**Comment by elllusion** [comment]
国内已经全网（电信、移动、联通、铁通）全域（全国各地）封杀了OpenAI提供api服务的域名和IP，也就是说已经被防火长城给列入域名和IP地址的黑名单了，封杀的速度非常快当天发布就当天封杀。 想要使用得使用魔法翻墙但国内使用翻墙要承担违法风险。

**Comment by bxs17** [comment]
只是因为被墙导致的错误吗 。。。。应该是 请求超时才对 但是这个错误是 panic: runtime error: invalid memory address or nil pointer dereference

**Comment by elllusion** [comment]
是由于被墙才出这个错误，ChatGPT部分使用的是这个项目 https://github.com/AlmazDelDiablo/gpt3-5-turbo-go， 你去拉他的代码编译看看能不能跑得通。估计也是同样的问题，昨晚我调试过了是没有返回数据而导致的错误。

**Comment by bxs17** [comment]
ok 我先开梯子测试

**Comment by bxs17** [comment]
![image](https://user-images.githubusercontent.com/23467964/222828771-384314fe-d203-4948-8432-feecca01df25.png)
不是墙的原因

**Comment by elllusion** [comment]
这段代码是打印服务器返回数据， 你调试以下看看是不是resp为空。。。有返回这是有数据的。index out of range  已经说明了没有数据返回导致不能索引数据。代码是直接copy那个项目的，只是添加了return把数据返回给handlers处理。

如果网络正常 response将会得到一个类似这样结构的json消息
```json
 {
  'id': 'chatcmpl-6p9XYPYSTTRi0xEviKjjilqrWU2Ve',
  'object': 'chat.completion',
  'created': 1677649420,
  'model': 'gpt-3.5-turbo',
  'usage': {'prompt_tokens': 56, 'completion_tokens': 31, 'total_tokens': 87},
  'choices': [
    {
    'message': {
       'role': 'assistant',
       'content': '2014年世界杯足球赛在巴西举办。'},
       'finish_reason': 'stop',
       'index': 0
    }
   ]
}
```

**Comment by bxs17** [comment]
知道发送的json应该什么格式吗 ？ 我直接post 到API试试 我看文档 没有  之前达芬奇还有或者其他模型是    {"model": "text-ada-001", "prompt": "今天日期", "temperature": 0, "max_tokens": 7}

**Comment by elllusion** [comment]
看README.md， 在最下面有咋实现连续对话的例子，那就是要发送的json格式。

**Comment by Tangkai9383** [comment]
> ![image](https://user-images.githubusercontent.com/23467964/222828771-384314fe-d203-4948-8432-feecca01df25.png) 不是墙的原因

我也是这个问题，突然就没有回复了，但是看openAI里面，也没说key有问题。

**Comment by elllusion** [comment]
> > ![image](https://user-images.githubusercontent.com/23467964/222828771-384314fe-d203-4948-8432-feecca01df25.png) 不是墙的原因
> 
> 我也是这个问题，突然就没有回复了，但是看openAI里面，也没说key有问题。

等梯子恢复正常在处理

**Comment by elllusion** [comment]
> > > ![image](https://user-images.githubusercontent.com/23467964/222828771-384314fe-d203-4948-8432-feecca01df25.png) 不是墙的原因
> > 
> > 
> > 我也是这个问题，突然就没有回复了，但是看openAI里面，也没说key有问题。
> 
> 等梯子恢复正常在处理

我这边直接下载编译后运行是一切正常的。。。没你们说的那些问题

![屏幕截图 2023-03-15 074511](https://user-images.githubusercontent.com/2971929/225167031-23e77594-447e-412a-9985-8f1f80fb6191.png)

**Comment by elllusion** [comment]
调试也是有数据返回的
![屏幕截图 2023-03-15 075424](https://user-images.githubusercontent.com/2971929/225167691-48a1f1ea-d2e5-4909-b35d-23bcb6e5c46a.png)

**Comment by elllusion** [comment]
综上， 出现问题要么是没用梯子要么是没openai的帐号 否则是可以正常使用的。以后在有任何问题一概不处理。自己编译有问题就fork一份代码然后用actions云编译。
